[package]
<<<<<<< HEAD
name = "endoflife"
=======
name = "even"
>>>>>>> 603bfc9 (Just a try)
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
=======
>>>>>>> 603bfc9 (Just a try)
